# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 150f16e84ce3ca1392513e27963d37ed4e3efdd88d5bc34be72ad15e85a287651d2d2f00cd0eebb391298ef0aa0da5ae7c89fe3aff3b135e4dec2e13c664d16e

test:
  secret_key_base: d8ccee5cdfccad8a5f52a97e69d09919d372cf98c59fabbc59918ba62d4d3188ee9aa073602d1e5d7c6ba00074d8198b5204878ddfd19c3e1439ef0f44444323

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
